* Emacs Guides
  This repository saved the basic usage of GNU/Emacs and my personal experience.

  *Note*: More practice are not just look at sentences, it's can helps you learn quickly!

  My Emacs configuration files are [[https://github.com/KiteAB/.emacs.d][these]], BTW.

  [[./README_cn.org][中文版]]

** Table of Contents
   * [[#contributors][Contributors]]
   * [[#basics-in-basic][Basics in Basic]]
     - [[#explore-files][Explore Files]]
     - [[#number-argument][Number Argument]]
     - [[#disabled-commands][Disabled Commands]]
   * [[#window-management][Window Management]]
   * [[#references][References]]
   * [[#license][License]]

** Contributors
   Thanks all contributors about this repository! (Rank order of contribution date)
   | Contributors | Emacs Configuration Files Repository |
   |--------------+--------------------------------------|
   | [[https://github.com/KiteAB][KiteAB]]       | [[https://github.com/KiteAB/.emacs.d][.emacs.d]]                             |

** Basics in Basic
   In Emacs, we have a rule:
   | Keybindings | Means                                                  |
   |-------------+--------------------------------------------------------|
   | ~C-<char>~  | Press control key when entering the ~<char>~ character |
   | ~M-<char>~  | Press alt key when entering the ~<char>~ character     |
   | ~s-<char>~  | Press super key when entering the ~<char>~ character   |

   Example:
   #+begin_example
   C-f means press control and enter "f" character
   M-x means press alt and enter "x" character
   s-a means press super and enter "a" character (Seldom used)
   #+end_example

   And you sometimes encounter multiple consecutive key combinations, example: ~C-x C-c~ to exit the Emacs.

   If you want to exit some running command, use ~C-g~ to exit them.

   You can try press ~M-x~ key, It'll open a "toolbox", you can find all Emacs command in it.

*** Explore Files
   You can use ~C-f~ ~C-b~ ~C-n~ ~C-p~ keybindings to move cursor slowly:
   | Keybindings | Actions         |
   |-------------+-----------------|
   | ~C-f~       | Forward a char  |
   | ~C-b~       | Backward a char |
   | ~C-n~       | Next line       |
   | ~C-p~       | Previous line   |

-----

   And you can use ~M-f~ ~M-b~ to move cursor by words:
   | Keybindings | Actions         |
   |-------------+-----------------|
   | ~M-f~       | Forward a word  |
   | ~M-b~       | Backward a word |

-----

   *What? Not fast enough?* Try page up or page down by ~C-v~ ~M-v~:
   | Keybindings | Actions   |
   |-------------+-----------|
   | ~C-v~       | Page Down |
   | ~M-v~       | Page Up   |
   (Or you still can page up and page down by ~<PGUP>~ and ~<PGDN>~ keys)

-----

   If you want the current line in a different location on the screen, you can use ~C-l~:
   | Keybindings         | Actions                                  |
   |---------------------+------------------------------------------|
   | ~C-l~ (first time)  | Re-center current line                   |
   | ~C-l~ (second time) | Put current line to top in the screen    |
   | ~C-l~ (third time)  | Put current line to bottom in the screen |

-----

   ~C-a~ ~C-e~ ~M-a~ ~M-e~ can help you fast move cursor to beginning of line or end of line, sentences can do that too:
   | Keybindings | Actions               |
   |-------------+-----------------------|
   | ~C-a~       | Beginning of line     |
   | ~C-e~       | End of line           |
   | ~M-a~       | Beginning of sentence |
   | ~M-e~       | End of sentence       |

-----

   And ~M-<~ ~M->~ is the fastest:
   | Keybindings | Actions           |
   |-------------+-------------------|
   | ~M-<~       | Beginning of file |
   | ~M->~       | End of file       |

-----

*** Number Argument
    You can add a number argument for some commands.
    | Keybindings       | Actions                       |
    |-------------------+-------------------------------|
    | ~C-u <num> <cmd>~ | Execute ~<num>~ times ~<cmd>~ |
    Here is an example:
    #+begin_example
    "C-u 8 C-n" means do "C-n" 8 times, which's cursor down 8 lines.
    #+end_example

-----

*** Disabled Commands
    Emacs has some disabled commands, they're dangerous commands, so Emacs disabled it.
    
    If you press ~C-x C-n~, Emacs will create a buffer named ~*Disabled Command*~, and you can enter ~y~ to enable this command or ~n~ to continue disable it.

** Window Management
   You can use some keybindings to manage your windows in Emacs.
   | Keybindings | Actions                           |
   |-------------+-----------------------------------|
   | ~C-x 0~     | Close current window (Not buffer) |
   | ~C-x 1~     | Leaving only the current window   |
   | ~C-x 2~     | Horizontal split a window         |
   | ~C-x 3~     | Vertical split a window           |

** References
   Emacs Tutorial: ~C-h t~ in Emacs, Emacs built-in tutorial

** License
   GPL-3.0
