* Emacs Guides
  This repository saved a way to use my personal experiences and basic usage with GNU/Emacs.

** Table of Contents
   * [[#foundation-in-foundation][Foundation in Foundation]]
     - [[#cursor-movement][Cursor Movement]]
   * [[#references][References]]
   * [[#license][License]]

** Foundation in Foundation
   In Emacs, we have a rule:
   | Keybindings | Means                                                  |
   |-------------+--------------------------------------------------------|
   | ~C-<char>~  | Press control key when entering the ~<char>~ character |
   | ~M-<char>~  | Press alt key when entering the ~<char>~ character     |
   | ~s-<char>~  | Press super key when entering the ~<char>~ character   |
   Example:
   #+begin_example
   C-f means press control and enter "f" character
   M-x means press alt and enter "x" character
   s-a means press super and enter "a" character (Seldom used)
   #+end_example

   And you sometimes encounter multiple consecutive key combinations, example: ~C-x C-c~ to exit the Emacs.

   If you want to exit some running command, use ~C-g~ to exit them.

   You can try press ~M-x~ key, It'll open a "toolbox", you can find all Emacs command in it.

*** Cursor Movement
   You can use ~C-f~ ~C-b~ ~C-n~ ~C-p~ keybindings to move cursor slowly:
   | Keybindings | Actions         |
   |-------------+-----------------|
   | ~C-f~       | Forward a char  |
   | ~C-b~       | Backward a char |
   | ~C-n~       | Next line       |
   | ~C-p~       | Previous line   |

   And you can use ~M-f~ ~M-b~ to move cursor by words:
   | Keybindings | Actions         |
   |-------------+-----------------|
   | ~M-f~       | Forward a word  |
   | ~M-b~       | Backward a word |

   What? Not fast enough? Try page up or page down by ~C-v~ ~M-v~:
   | Keybindings | Actions   |
   |-------------+-----------|
   | ~C-v~       | Page Down |
   | ~M-v~       | Page Up   |
   (Or you still can page up and page down by ~<PGUP>~ and ~<PGDN>~ keys)

** References
   Emacs Tutorial: ~C-h t~ in Emacs, Emacs built-in tutorial

** License
   GPL-3.0
